<template>
    <div class="loadingio-spinner-cube-n3cvngfry3q">
        <div class="ldio-lckkun9qkzq">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</template>

<script>
export default{
    name: 'AppLoader',
}
</script>

<style lang="scss">

</style>


    <style type="scss">
    @keyframes ldio-lckkun9qkzq {
      0% { transform: scale(1.1500000000000001) }
      100% { transform: scale(1) }
    }
    .ldio-lckkun9qkzq div {
      position: absolute;
      width: 80px;
      height: 80px;
      top: 13.333333333333336px;
      left: 13.333333333333336px;
      background: #1d0e0b;
      animation: ldio-lckkun9qkzq 1s cubic-bezier(0,0.5,0.5,1) infinite;
      animation-delay: -0.3s;
    }
    .ldio-lckkun9qkzq div:nth-child(2) {
      top: 13.333333333333336px;
      left: 106.66666666666666px;
      background: #774023;
      animation-delay: -0.2s;
    }
    .ldio-lckkun9qkzq div:nth-child(3) {
      top: 106.66666666666666px;
      left: 13.333333333333336px;
      background: #f3e7c9;
      animation-delay: 0s;
    }
    .ldio-lckkun9qkzq div:nth-child(4) {
      top: 106.66666666666666px;
      left: 106.66666666666666px;
      background: #d88c51;
      animation-delay: -0.1s;
    }
    .loadingio-spinner-cube-n3cvngfry3q {
      width: 200px;
      height: 200px;
      display: inline-block;
      overflow: hidden;
      background: #f1f2f3;
    }
    .ldio-lckkun9qkzq {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-lckkun9qkzq div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
    </style>